# Generated by Django 4.0.3 on 2022-04-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200, verbose_name='Имя студента')),
                ('ball1', models.CharField(max_length=200, verbose_name='Баллы за 1 дисциплину')),
                ('ball2', models.CharField(max_length=200, verbose_name='Баллы за 2 дисциплину')),
                ('ball3', models.CharField(max_length=200, verbose_name='Баллы за 3 дисциплину')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=200, verbose_name='Имя преподавателя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={},
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='average',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='total',
        ),
    ]
