# Generated by Django 4.0.3 on 2022-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_teacher_alter_discipline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='nameteacher',
            field=models.CharField(default='', max_length=200, verbose_name='Имя преподавателя'),
            preserve_default=False,
        ),
    ]
